import urllib.request
import json
import os

URL = "http://localhost/goobrules/rules.json"
OUTPUT_FILE = "Resources\ServerInfo\Guidebook\ServerRules\\ServerRules.xml"

try:
    print(f"Fetching JSON from {URL}...")
    with urllib.request.urlopen(URL) as response:
        data = json.load(response)
except Exception as e:
    print(f"Failed to fetch or parse JSON: {e}")
    exit(1)

rules = data.get("rules", [])

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("<!-- This file is automatically generated. Changes will be lost. -->\n\n")
    f.write("<Document>\n")

    f.write("# Goobstation Rules\n")
    f.write("Space Station 14 is not like most games. Many rules are designed to require roleplay, and not all rules are intuitive. Please take the time to read and understand the rules before you play so that you aren't surprised. Some of our rules are zero tolerance rules, meaning that a violation will result in an indefinite ban without any warning. Game admins will treat you as if you have read the rules, even if you have not.\n\n")

    for i, rule in enumerate(rules):
        title = rule.get("title", "(No Title)")
        description = rule.get("description", "")
        examples = rule.get("examples", [])
        zero_tolerance = rule.get("zeroTolerance", False)

        f.write(f"### Rule {i}: {title}\n")
        f.write(f"{description}\n")
        if zero_tolerance:
            f.write("\n[color=#EB2D3A]This is a zero-tolerance rule; if broken, it will result in an immediate permanent ban.[/color]\n")

        if examples:
            f.write("\n[color=#a88b5e][bold]Examples:[/bold][/color]\n")
            for e, ex in enumerate(examples):
                f.write(f"\n- \n{ex}\n")

        f.write("\n")
    f.write("</Document>\n")

print(f"Done. Output saved to {os.path.abspath(OUTPUT_FILE)}")
