import urllib.request
import json
import os

URL = "http://localhost/goobrules/rules.json"
OUTPUT_FILE = "Resources\ServerInfo\Guidebook\ServerRules\CoreRules\\ServerRules.xml"

try:
    print(f"Fetching JSON from {URL}...")
    with urllib.request.urlopen(URL) as response:
        data = json.load(response)
except Exception as e:
    print(f"Failed to fetch or parse JSON: {e}")
    exit(1)

rules = data.get("rules", [])

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("<!-- This file is automatically generated. Changes will be lost. -->")
    f.write("<Document>\n")
    for i, rule in enumerate(rules):
        title = rule.get("title", "(No Title)")
        description = rule.get("description", "")
        examples = rule.get("examples", [])
        zero_tolerance = rule.get("zeroTolerance", False)

        f.write(f"# Rule {i}: {title}\n")
        f.write(f"{description}\n")
        if zero_tolerance:
            f.write("\nThis is a zero-tolerance rule; if broken, it will result in an immediate permanent ban.\n")

        if examples:
            f.write("## Examples:\n")
            for e, ex in enumerate(examples):
                f.write(f"Example {e + 1}:\n{ex}\n")

        f.write("\n")
    f.write("</Document>\n")

print(f"Done. Output saved to {os.path.abspath(OUTPUT_FILE)}")
